name: Release
on: [workflow_dispatch] # Manual trigger
jobs:
  build:
    runs-on: ubuntu-20.04
    container:
      image: openjdk:15-jdk
      options: --user root
    steps:
      - uses: actions/checkout@v1
      - uses: gradle/wrapper-validation-action@v1
      - run: ./gradlew checkVersion publish curseforge --stacktrace
        env:
          CURSEFORGE_API_KEY: ${{ secrets.CURSEFORGE_API_KEY }}
          MAVEN_PUBLISH_TOKEN: ${{ secrets.MAVEN_PUBLISH_TOKEN }}
